name: Monorepo release
description: Akce pro vytvoření release pro P7 produkty

inputs:
  version:
    description: 'Version (patch|minor|major|first-minor)'
    required: true
  gh-token:
    required: true
    description: "GitHub token"
  dry-run:
    description: "Spustí release v režimu dry-run (true|false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Validate dry-run input
      id: dryrun
      shell: bash
      run: |
        DRYRUN="${{ inputs.dry-run }}"
        case "$DRYRUN" in
          true|false) ;;
          *) echo "::error::Invalid dry-run value: $DRYRUN (allowed: true|false)"; exit 1 ;;
        esac

    - name: Stage Check
      id: stage
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        case "$VERSION" in
          patch) echo "stage=patch" >> "$GITHUB_OUTPUT" ;;
          minor|major|first-minor) echo "stage=release" >> "$GITHUB_OUTPUT" ;;
          *) echo "::error::Unknown version type: $VERSION"; exit 1 ;;
        esac

    - name: Detect if repository is already checked out
      id: detect
      shell: bash
      run: |
        set -euo pipefail
        has_checkout=false
        if git -C "$GITHUB_WORKSPACE" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          has_checkout=true
        fi
        echo "has_checkout=$has_checkout" >> "$GITHUB_OUTPUT"

    - name: actions/checkout (only if missing)
      if: ${{ steps.detect.outputs.has_checkout != 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Git user
      shell: bash
      run: |
        # Ošetříme safe.directory (aby Git nehlásil dubious ownership)
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        # Pokud jsme uvnitř repozitáře, použijeme --local
        if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "action@github.com"
        else
          # Fallback – použijeme globální konfiguraci
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "action@github.com"
        fi

    - name: Configure Git auth for GitHub (fallback na git clone)
      shell: bash
      run: |
        # 1) Composer: přidej HTTP Basic (vedle stávajícího github-oauth)
        printf '%s\n' 'COMPOSER_AUTH={"github-oauth":{"github.com":"${{ inputs.gh-token }}"},"http-basic":{"github.com":{"username":"x-access-token","password":"${{ inputs.gh-token }}"}},"github-protocols":["https"]}' >> "$GITHUB_ENV"

        # 2) Nastavení composer timeout na 20 minut
        printf '%s\n' 'COMPOSER_PROCESS_TIMEOUT=1200' >> "$GITHUB_ENV"

        # 3) Přesměruj https/ssh GitHub URL na https s tokenem - preferuj lokálně, pokud jsme v GIT repo
        if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          git config --local url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "https://github.com/"
          git config --local url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "git@github.com:"
          git config --local url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "ssh://git@github.com/"
        else
          git config --global url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://x-access-token:${{ inputs.gh-token }}@github.com/".insteadOf "ssh://git@github.com/"
        fi

    - name: Composer Install
      uses: ramsey/composer-install@v2
      with:
        composer-options: "--optimize-autoloader --prefer-dist"
      env:
        COMPOSER_PROCESS_TIMEOUT: 1200
        # POZOR: Nepředáváme 'github-token', aby se to nebilo s COMPOSER_AUTH.
        COMPOSER_AUTH: >-
          {
            "github-oauth":{"github.com":"${{ inputs.gh-token }}"},
            "http-basic":{"github.com":{"username":"x-access-token","password":"${{ inputs.gh-token }}"}},
            "github-protocols":["https"]
          }

    - name: Compute version argument
      id: varg
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "first-minor" ]; then
          echo "value=0.1.0" >> "$GITHUB_OUTPUT"
        else
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"
        fi

    - name: Release
      shell: bash
      run: |
        VERSION_ARG="${{ steps.varg.outputs.value }}"
        CMD="vendor/bin/monorepo-builder release $VERSION_ARG --stage ${{ steps.stage.outputs.stage }}"
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          CMD="$CMD --dry-run"
        fi
        echo "Running: $CMD"
        eval "$CMD"
