name: Split Monorepo v2 – Workflow dispatch

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      package:
        description: 'Název package'
        required: true
        type: choice
        options: #Je potřeba definovat konkrétní balíček pro které se spouští split
          - 'package-sdk'
          - 'package-admin'

concurrency:
  group: split_monorepo-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  split-branch:
    uses: peckadesign/.github/.github/workflows/split_monorepo.yaml@v1
    name: Split
    with:
      package:  ${{ inputs.package }}
      organization: "peckadesign"
      force: ${{ inputs.force == 'true' }}
      push-tags:  ${{ github.ref != 'refs/heads/master' }}
    secrets:
      gh-token: # GITHUB Token
