## Workflow for P7products - with Github authentication APP
name: Monorepo release
run-name: Monorepo release - ${{ inputs.version }} version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'patch'

jobs:
  release:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    name: Monorepo release
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.P7_CI_APP_ID }}
          private-key: ${{ secrets.P7_CI_APP_PRIVATE_KEY }}
          # optional: owner not needed IF the app has access to the repo running the workflow
          #   if you get 'RequestError [HttpError]: Not Found 404', pass in owner
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: peckadesign/.github/.github/actions/p7-monorepo-release@v1
        with:
          version: ${{ inputs.version }}
          gh-token: ${{ steps.app-token.outputs.token }}
