name: Split Monorepo v2

on:
  push:
    branches:
      - master
    tags:
      - '*'

concurrency:
  group: split_monorepo-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  split-branch:
    uses: peckadesign/.github/.github/workflows/split_monorepo.yaml@v1
    name: Split
    strategy:
      fail-fast: false
      matrix:
        package:
          - package-data-exchange
          - package-sdk
    with:
      package: ${{ matrix.package }}
      organization: "peckadesign"
      push-tags:  ${{ github.ref != 'refs/heads/master' }}
    secrets:
      gh-token: # GITHUB Token
