## Workflow for P7products - with Github authentication APP
name: Creating a release for a new tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.0' # Triggered only for major + minor tags

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Creating release
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.P7_CI_APP_ID }}
          private-key: ${{ secrets.P7_CI_APP_PRIVATE_KEY }}
          # optional: owner not needed IF the app has access to the repo running the workflow
          #   if you get 'RequestError [HttpError]: Not Found 404', pass in owner
          owner: ${{ github.repository_owner }}

      - uses: peckadesign/.github/.github/actions/p7-release-drafter@v1
        with:
          tag: ${{ github.ref_name }}
          publish: true
          latest: true
          gh-token: ${{ steps.app-token.outputs.token }}

#  #deprecated
#  release-with-gh-token:
#    timeout-minutes: 10
#    runs-on: ubuntu-latest
#    name: Creating release
#    steps:
#      - uses: peckadesign/.github/.github/actions/p7-release-drafter@v1
#        with:
#          tag: ${{ github.ref_name }}
#          publish: true
#          latest: true
#          gh-token: # GITHUB Token. Monorepo usage note: For split sub-packages, you need to enable access scope "workflow (Update GitHub Action workflows)" for access token.
