name: CodingStandard

on:
  workflow_call:
    inputs:
      php:
        required: false
        type: string
        default: "8.1"
jobs:
  cs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Coding standard
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ inputs.php }}"

      - name: Secret export
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: CS
        run: make cs
