name: Monorepo release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'

jobs:
  assert:
    runs-on: ubuntu-latest
    name: Assert required inputs
    timeout-minutes: 5
    steps:
      - name: Check for Secrets and Inputs
        id: inputs-check
        shell: bash
        run: |
          if [ "${{ inputs.version }}" == '' ]; then
            echo "is-valid=false" >> $GITHUB_OUTPUT;
            echo "msg=version" >> $GITHUB_OUTPUT;
          else
            echo "is-valid=true" >> $GITHUB_OUTPUT;
            echo "msg=" >> $GITHUB_OUTPUT;
          fi
      - name: Result
        if: ${{ steps.inputs-check.outputs.is-valid != 'true' }}
        shell: bash
        run: |
          echo "::error Not valid input ${{ steps.inputs-check.outputs.msg}}"
          exit 1
  release:
    needs: assert
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_WORKFLOW }}

      - run: git config --global user.name "GitHub Action"
      - run: git config --global user.email "action@github.com"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Secret export
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Release
        run: vendor/bin/monorepo-builder release ${{ inputs.version }}
