name: Release drafter (P7)

on:
  workflow_call:
    inputs:
      tag:
        description: Tag
        required: true
        type: string
      latest:
        description: Latest
        required: false
        type: boolean
        default: false
      publish:
        description: Auto Publish
        required: false
        type: boolean
        default: false
    secrets:
      gh-token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Creating release
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.gh-token }}

      - name: Get the tag branch
        id: check_branch
        # 1. Get the list of branches ref where this tag exists
        # 2. Remove 'origin/' from that result
        # 3. Put that string in output
        # => We can now use function 'contains(list, item)''
        run: |
          raw=$(git branch -r --contains ${{ inputs.tag }})
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch"
      - name: Draft release
        uses: release-drafter/release-drafter@v5
        id: draft_release
        with:
          config-name: p7_release_drafter_config.yaml
          tag: ${{ inputs.tag }}
          version: v${{ inputs.tag }}
          disable-autolabeler: true
          latest: ${{ inputs.latest }}
          publish: ${{ inputs.publish }}
          commitish: ${{ steps.check_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
